#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'

clear
	
    echo -e "${GREEN}  +------------------------------------------------------------------+ " 
    echo -e "${LIGHTBLUE}  # ${RED}Version${GREEN} 1.0${LIGHTBLUE} |${CYAN}           NGINX Exploit${LIGHTBLUE}                            # "
	echo -e "${LIGHTBLUE}  # ------------          --------------------                       # "
    echo -e "${LIGHTBLUE}  #${CYAN}                          Auto installer${LIGHTBLUE}                          # "
	echo -e "${LIGHTBLUE}  #                          --------------                          # "
	echo -e "${LIGHTBLUE}  #${CYAN}                              Enjoy${LIGHTBLUE}                               # "
	echo -e "${LIGHTBLUE}  #                              -----                               # "
	echo -e "${LIGHTBLUE}  #${CYAN}                      Press Enter For Install${LIGHTBLUE}                     # "
    echo -e "${GREEN}  +------------------------------------------------------------------+ "
    	
echo -e "${LIGHTBLUE}Press Enter To Start Installing Python On YourServer!"
read enter
yum install python -y
yum install nmap
yum install unzip
yum update -y
yum install gcc -y
gcc -pthread scanner.c -o scanner

./installed